spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&userSSl=false
    jpa:
      show-sql: true
dev: test001

girl:
  name: Anta
  age: 17
